### PR TITLE
project setup

### PR DESCRIPTION
**Pull request by kenny-67**
- Switched to Reactjs
- added a basic express server to the backend
- created the base folder structure

### CODE REVIEW

**Review by Mallamin — COMMENTED** [review]
Great. Just wondering if you discussed this switch with the TL

**Comment by abdulsalamcodes** [comment]
The DevOp dev also mentioned he had some issues deploying React apps and he is glad we used Next. I think we should bring him into the discussion too before deciding on merging.

**Comment by Mallamin** [comment]
> The DevOp dev also mentioned he had some issues deploying React apps and he is glad we used Next. I think we should bring him into the discussion too before deciding on merging.

Well, that's complicated because our stack is React/NodeJs...

**Comment by abdulsalamcodes** [comment]
Okay then, I think we can go ahead and merge it. @Mallamin .
Thanks @kenny-67

**Review by Mallamin — APPROVED** [review]

**Review by abdulsalamcodes — APPROVED** [review]

**Comment by Mallamin** [comment]
> @Mallamin yes mavello already approved it
> @abdulsalamcodes I already spoke with the DevOps guy and he said I should go ahead and tell him when I'm done

@kenny-67 approved

**Comment by abdulsalamcodes** [comment]
I can then merge it @Mallamin ?

**Review by moki-daniel — COMMENTED** [review]
To me the setup looks okay, a quick one are we using both react and next for development

**Review by moki-daniel — APPROVED** [review]

**Comment by kenny-67** [comment]
Test link http://whiteboard.zuri.chat/

**Comment by abdulsalamcodes** [comment]
@kenny-67  I think we should update the README.md file to have this link and other details like the Figma link and what is required as regards contributing to the project.

**Pull request merged**
